spring.application.name=ch12-mcp-stdio-server

# MCP Server
spring.ai.mcp.server.name=ch12-mcp-stdio-server
spring.ai.mcp.server.version=0.0.1
spring.ai.mcp.server.stdio=true

# 웹 서버로 실행하지 않음
spring.main.web-application-type=none

# STDIO 통신에 배너가 섞이지 않도록 설정
spring.main.banner-mode=off