spring.application.name=ch06

# OpenAI API KEY
spring.ai.openai.api-key=${OPENAI_API_KEY}

spring.ai.model.chat=ollama
spring.ai.ollama.base-url=https://desktop-sg99cdv.taile1d990.ts.net
spring.ai.ollama.chat.model=gemma3:4b
spring.ai.ollama.chat.temperature=0.7
spring.ai.ollama.chat.num-ctx=4096