spring.application.name=ch04

spring.ai.openai.api-key=${NVIDIA_API_KEY}

spring.ai.openai.base-url=https://integrate.api.nvidia.com

spring.ai.openai.chat.options.model=deepseek-ai/deepseek-v4-flash
spring.ai.openai.chat.options.temperature=1.0
spring.ai.openai.chat.options.top-p=0.95
spring.ai.openai.chat.options.max-tokens=16384