spring.application.name=ch12-mcp-sse-client

server.port=8080

# Ollama
spring.ai.model.chat=ollama
spring.ai.ollama.base-url=http://100.84.170.5:11434

spring.ai.ollama.chat.model=qwen3:4b
spring.ai.ollama.chat.think=false
spring.ai.ollama.chat.temperature=0.2
spring.ai.ollama.chat.num-ctx=4096
spring.ai.ollama.chat.num-predict=512

spring.ai.model.embedding=none

# 8081에서 실행 중인 MCP SSE Server 연결
spring.ai.mcp.client.type=SYNC
spring.ai.mcp.client.sse.connections.server1.url=http://localhost:8081
spring.ai.mcp.client.sse.connections.server1.sse-endpoint=/sse
spring.ai.mcp.client.request-timeout=60s

# Logging
logging.level.org.springframework.ai.chat.client.advisor=DEBUG
logging.level.org.springframework.ai.mcp=DEBUG
logging.level.io.modelcontextprotocol=DEBUG